### ISSUE TITLE
AI satellite robotic storage console is missing.

### ISSUE THREAD

**Issue by Spacemanspark** [StratusSS13/Stratus#14]
**Problem Description**:
There's no robotic storage console for the robotic storage unit in the AI satellite. Admins have to create one every round for the time being.
![](http://image.prntscr.com/image/90d58c1a3d464db19be6f0e78e84959f.png)

**Comment by pipextiny** [comment]
I think this one has been fixed by goblet in the WIP map that is now on live

**Comment by FlattestGuitar** [comment]
We're gonna have a new map anyway. No point keeping this around.
