### ISSUE TITLE
Latest runtime

### ISSUE THREAD

**Issue by SomanBat** [StratusSS13/Stratus#21]
Runtime from daemon. Seems consistent.  Go nuts coder friends.

[09:34:12] Runtime in new_player.dm,256: Cannot read 
 proc name: IsJobAvailable (/mob/new_player/proc/IsJobAvailable)
  usr: FiregunnZ (firegunnz) (/mob/new_player)
  usr.loc: The floor (8,174,2) (/turf/unsimulated/floor)
  src: FiregunnZ (/mob/new_player)
  src.loc: the floor (8,174,2) (/turf/unsimulated/floor)
  call stack:
  FiregunnZ (/mob/new_player): IsJobAvailable("Civilian")
  FiregunnZ (/mob/new_player): LateChoices()
  FiregunnZ (/mob/new_player): Topic("src=\[0x3000059]_150;late_join...", /list (/list))
  FiregunnZ (/client): Topic("src=\[0x3000059]_150;late_join...", /list (/list), FiregunnZ (/mob/new_player))

**Comment by Codingale** [comment]
Broken from #8 due to the fact Line 256 was changed but not Lines 253/254.


https://github.com/StratusSS13/Stratus/blob/master/code/modules/mob/new_player/new_player.dm#L253-L256
